const actionTypes = {
    GET_POSTS_AJAX_CALL_START : 'GET_POSTS_AJAX_CALL_START',
    GET_POSTS_AJAX_CALL_SUCCESS: 'GET_POSTS_AJAX_CALL_SUCCESS',
    GET_POSTS_AJAX_CALL_FAILURE: 'GET_POSTS_AJAX_CALL_FAILURE',
    GET_POSTS: 'GET_POSTS',
    
    GET_AUTHORS_AJAX_CALL_START: 'GET_AUTHORS_AJAX_CALL_START',
    GET_AUTHORS_AJAX_CALL_SUCCESS: 'GET_AUTHORS_AJAX_CALL_SUCCESS',
    GET_AUTHORS_AJAX_CALL_FAILURE: 'GET_AUTHORS_AJAX_CALL_FAILURE',
    GET_AUTHORS: 'GET_AUTHORS',
};

export default actionTypes;