const actionTypes = {
    GET_POSTS_AJAX_CALL_START : 'GET_POSTS_AJAX_CALL_START',
    GET_POSTS_AJAX_CALL_SUCCESS: 'GET_POSTS_AJAX_CALL_SUCCESS',
    GET_POSTS_AJAX_CALL_FAILURE: 'GET_POSTS_AJAX_CALL_FAILURE',
    GET_POSTS: 'GET_POSTS',
    
};

export default actionTypes;